// vault today — ephemeral working-memory artifact (Vault/Today.md).
//
// Today.md is a regenerated derived view of "what is true right now" — calendar,
// open commitments, last-24h voice memos, Open Threads from active venture
// _learnings.md files. It is NOT memory. Memory persists; Today.md is overwritten
// every regen cycle. Sibling artifact to Playbooks-Index.md (also regenerated).
//
// Deterministic operations live here. Regeneration shells out to the hook script
// because it requires LLM judgment via headless claude (calendar/Todoist/Open
// Threads aggregation that bash cannot do alone).

import { existsSync, readFileSync, statSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { TODAY_FILE, HOOK_GENERATE_TODAY } from '../lib/config.js';
import { emit, fail, info } from '../lib/output.js';

const HELP = `vault today — ephemeral working-memory artifact (Vault/Today.md)

Usage:
  vault today path                  Print absolute path to Today.md
  vault today read                  Print Today.md contents to stdout
  vault today stale [--max N]       Exit 1 if older than N hours (default 6)
  vault today regenerate            Invoke generate-today.sh (shells out to claude -p)
  vault today --help

Today.md is regenerated by ~/.claude/hooks/generate-today.sh, which is
launchd-driven at 7:15am, 11am, 2pm, 5pm PT on weekdays. Read first when
the task is time-sensitive.
`;

export async function dispatchToday(args) {
  if (args.length === 0 || args[0] === '--help') {
    process.stdout.write(HELP);
    return;
  }
  const sub = args[0];
  const rest = args.slice(1);
  switch (sub) {
    case 'path':
      await pathCmd(rest);
      break;
    case 'read':
      await readCmd(rest);
      break;
    case 'stale':
      await staleCmd(rest);
      break;
    case 'regenerate':
      await regenerateCmd(rest);
      break;
    default:
      fail(`unknown today subcommand: ${sub}`);
  }
}

async function pathCmd(args) {
  emit({ path: TODAY_FILE, exists: existsSync(TODAY_FILE) }, args);
}

async function readCmd(args) {
  if (!existsSync(TODAY_FILE)) {
    fail(`Today.md not found at ${TODAY_FILE}. Run \`vault today regenerate\`.`);
  }
  const content = readFileSync(TODAY_FILE, 'utf8');
  // For read, always emit the raw file content (not JSON-wrapped) to be useful
  // in cat | grep pipelines. --json explicitly opts into structured output.
  if (args.includes('--json')) {
    const stat = statSync(TODAY_FILE);
    emit({
      path: TODAY_FILE,
      mtime: stat.mtime.toISOString(),
      size: stat.size,
      lines: content.split('\n').length,
      content,
    }, args);
  } else {
    process.stdout.write(content);
  }
}

async function staleCmd(args) {
  const maxIdx = args.indexOf('--max');
  const maxHours = maxIdx >= 0 ? parseFloat(args[maxIdx + 1]) : 6;
  if (Number.isNaN(maxHours)) fail('--max must be a number (hours)');

  if (!existsSync(TODAY_FILE)) {
    emit({ stale: true, reason: 'file does not exist', max_hours: maxHours }, args);
    process.exit(1);
  }

  const stat = statSync(TODAY_FILE);
  const ageMs = Date.now() - stat.mtime.getTime();
  const ageHours = ageMs / (1000 * 60 * 60);
  const stale = ageHours > maxHours;

  emit({
    stale,
    age_hours: Number(ageHours.toFixed(2)),
    max_hours: maxHours,
    mtime: stat.mtime.toISOString(),
    path: TODAY_FILE,
  }, args);

  if (stale) process.exit(1);
}

async function regenerateCmd(args) {
  if (!existsSync(HOOK_GENERATE_TODAY)) {
    fail(`generate-today.sh not found at ${HOOK_GENERATE_TODAY}. Install vault-conventions or place the hook script.`);
  }
  info(`invoking ${HOOK_GENERATE_TODAY}`);
  const verbose = args.includes('--verbose');
  const result = spawnSync(HOOK_GENERATE_TODAY, verbose ? ['--verbose'] : [], {
    stdio: 'inherit',
  });
  if (result.status !== 0) {
    fail(`generate-today.sh exited ${result.status}`, result.status || 1);
  }
}
